//gambiarra ultimate
export default function requireImage(src: string) {
    switch (src) {
        case 'back-olive':
            return require('../assets/img/back-olive.png').default;
        case 'back-teal':
            return require('../assets/img/back-teal.png').default;
        case 'card-base':
            return require('../assets/img/card-base.png').default;
        case 'club_A':
            return require('../assets/img/club_A.png').default;
        case 'club_10':
            return require('../assets/img/club_10.png').default;
        case 'club_2':
            return require('../assets/img/club_2.png').default;
        case 'club_3':
            return require('../assets/img/club_3.png').default;
        case 'club_4':
            return require('../assets/img/club_4.png').default;
        case 'club_5':
            return require('../assets/img/club_5.png').default;
        case 'club_6':
            return require('../assets/img/club_6.png').default;
        case 'club_7':
            return require('../assets/img/club_7.png').default;
        case 'club_8':
            return require('../assets/img/club_8.png').default;
        case 'club_9':
            return require('../assets/img/club_9.png').default;
        case 'club_J':
            return require('../assets/img/club_J.png').default;
        case 'club_K':
            return require('../assets/img/club_K.png').default;
        case 'club_Q':
            return require('../assets/img/club_Q.png').default;
        case 'diamond_A':
            return require('../assets/img/diamond_A.png').default;
        case 'diamond_10':
            return require('../assets/img/diamond_10.png').default;
        case 'diamond_2':
            return require('../assets/img/diamond_2.png').default;
        case 'diamond_3':
            return require('../assets/img/diamond_3.png').default;
        case 'diamond_4':
            return require('../assets/img/diamond_4.png').default;
        case 'diamond_5':
            return require('../assets/img/diamond_5.png').default;
        case 'diamond_6':
            return require('../assets/img/diamond_6.png').default;
        case 'diamond_7':
            return require('../assets/img/diamond_7.png').default;
        case 'diamond_8':
            return require('../assets/img/diamond_8.png').default;
        case 'diamond_9':
            return require('../assets/img/diamond_9.png').default;
        case 'diamond_J':
            return require('../assets/img/diamond_J.png').default;
        case 'diamond_K':
            return require('../assets/img/diamond_K.png').default;
        case 'diamond_Q':
            return require('../assets/img/diamond_Q.png').default;
        case 'heart_A':
            return require('../assets/img/heart_A.png').default;
        case 'heart_10':
            return require('../assets/img/heart_10.png').default;
        case 'heart_2':
            return require('../assets/img/heart_2.png').default;
        case 'heart_3':
            return require('../assets/img/heart_3.png').default;
        case 'heart_4':
            return require('../assets/img/heart_4.png').default;
        case 'heart_5':
            return require('../assets/img/heart_5.png').default;
        case 'heart_6':
            return require('../assets/img/heart_6.png').default;
        case 'heart_7':
            return require('../assets/img/heart_7.png').default;
        case 'heart_8':
            return require('../assets/img/heart_8.png').default;
        case 'heart_9':
            return require('../assets/img/heart_9.png').default;
        case 'heart_J':
            return require('../assets/img/heart_J.png').default;
        case 'heart_K':
            return require('../assets/img/heart_K.png').default;
        case 'heart_Q':
            return require('../assets/img/heart_Q.png').default;
        case 'spade_A':
            return require('../assets/img/spade_A.png').default;
        case 'spade_10':
            return require('../assets/img/spade_10.png').default;
        case 'spade_2':
            return require('../assets/img/spade_2.png').default;
        case 'spade_3':
            return require('../assets/img/spade_3.png').default;
        case 'spade_4':
            return require('../assets/img/spade_4.png').default;
        case 'spade_5':
            return require('../assets/img/spade_5.png').default;
        case 'spade_6':
            return require('../assets/img/spade_6.png').default;
        case 'spade_7':
            return require('../assets/img/spade_7.png').default;
        case 'spade_8':
            return require('../assets/img/spade_8.png').default;
        case 'spade_9':
            return require('../assets/img/spade_9.png').default;
        case 'spade_J':
            return require('../assets/img/spade_J.png').default;
        case 'spade_K':
            return require('../assets/img/spade_K.png').default;
        case 'spade_Q':
            return require('../assets/img/spade_Q.png').default;
        case 'suit-club':
            return require('../assets/img/suit-club.png').default;
        case 'suit-diamond':
            return require('../assets/img/suit-diamond.png').default;
        case 'suit-heart':
            return require('../assets/img/suit-heart.png').default;
        case 'suit-spade':
            return require('../assets/img/suit-spade.png').default;
        default:
            throw new Error('Invalid image!');
    }
}